### ISSUE TITLE
TagCreator form - invalid values getting populated

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#102]
Invalid option gets populated for an enum field. Please see an example below.

![image](https://user-images.githubusercontent.com/8491735/199336437-cebf8895-1c26-49ef-aa95-2b2af8b9e5ce.png)

**Comment by yogeshVU** [comment]
another example: 
![image](https://user-images.githubusercontent.com/8491735/199336712-661edd82-5781-4825-8a50-26c243e9b281.png)

**Comment by brollb** [comment]
No longer an issue after the change in format used here.
