### ISSUE TITLE
tag conversion failing 

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#103]
Getting tag conversion error while downloading a freshly uploaded data from a repo. Here is the corresponding metadata.
![image](https://user-images.githubusercontent.com/8491735/199377007-cea76880-e667-412b-a352-848d0c83d796.png)
[tags (43).txt](https://github.com/webgme/webgme-taxonomy/files/9915205/tags.43.txt)

**Comment by brollb** [comment]
It appears that human-readable tags were uploaded to PDP without being converted to GUID format.
