### ISSUE TITLE
Not able to parse tags for the GUID conversion

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#109]
Conversion from human->GUID needs update to support the new taxonomy representation.
When user submits a json file containing tags to the TagFormat router, the router responds with ```"Tag not found: value```

Steps to reproduce error:
Create a json file from the TagCreator Form

![image](https://user-images.githubusercontent.com/8491735/200886993-9001e547-f6ac-4b84-b42a-9169b0ffe9e2.png)

```
{"taxonomyVersion":{"id":"AllLeap+Taxonomy","branch":"master","url":"wellcomewebgme.centralus.cloudapp.azure.com"},"taxonomyTags":[{"value":"Asian","Tag":"race"}]}
```

Upload this to the TagFormatter.

example curl command: 
```
curl --location --request GET 'https://wellcomewebgme.centralus.cloudapp.azure.com/routers/TagFormat/AllLeap%2BTaxonomy/branch/master/human?tags=%5B%7B%22value%22%3A%22Asian%22%2C%22Tag%22%3A%22race%22%7D%5D'
```
This also appears to be the case when user is uploading through the dashboard.

**Comment by brollb** [comment]
I believe you meant to convert them to guid format, correct? Currently, it is trying to convert human-readable tags to human-readable format. Try this:
```
curl --location --request GET 'https://wellcomewebgme.centralus.cloudapp.azure.com/routers/TagFormat/AllLeap%2BTaxonomy/branch/master/guid?tags=%5B%7B%22value%22%3A%22Asian%22%2C%22Tag%22%3A%22race%22%7D%5D'
```

**Comment by brollb** [comment]
This appears to be fixed in the current version.
