### ISSUE TITLE
Tag creator should be controlled by a content type if set for the taggable

### ISSUE THREAD

**Issue by kecso** [webgme/webgme-taxonomy#129]
Taggable elements should have a pointer that points to a content type.
If the content type is set, it should control what is offered in the tag creator visualizer (the terms of a vocabulary).

**Comment by brollb** [comment]
If no content type is set, it seems fine to allow it to be tagged with anything (ie, the current behavior). This maintains backwards compatibility and might make experimentation easier... Thoughts?

**Comment by kecso** [comment]
Exactly.
Sorry, I meant to write this into the initial description, but then I thought it is default :D
