### ISSUE TITLE
Simple term/label throws error

### ISSUE THREAD

**Issue by kecso** [webgme/webgme-taxonomy#133]
the cause is probably its transaltion.
Example: term with name 'LABEL'
currently it goes into the json as 'tag':"LABEL" instead of {'tag':"LABEL"} and it throws a bunch of errors

**Comment by brollb** [comment]
Can you post the error message, too?

**Comment by kecso** [comment]
sorry.
![image](https://user-images.githubusercontent.com/1371489/211156260-0ef65b82-2185-464b-b8b1-ad67fcea5d9a.png)

also attach the project, just in case
[guest+t4_f75988.zip](https://github.com/webgme/webgme-taxonomy/files/10366502/guest%2Bt4_f75988.zip)

**Comment by romancow** [comment]
@brollb Looking into this one and came across this comment: https://github.com/webgme/webgme-taxonomy/blob/main/src/common/TagCreatorForm.js#L45

Could this apply in this case? It looks like that `setMissingDefaults` is only being attached to the "Download" button and not the "Apply tags" button. And the resulting errors appear similar to what that comment describes.

I downloaded @kecso's attached project and could reproduce the error if I click "Apply tags" with the default selected "LABEL" option. But if I select something else, then click back to "LABEL", then I don't get these errors.

Do we maybe just need to call `setMissingDefaults` when "Apply tags" is clicked, like "Download"?

**Comment by romancow** [comment]
Going on the previous assumption, calling `setMissingDefaults` on "Apply tags". Pull request [here](https://github.com/webgme/webgme-taxonomy/pull/134). I'm no longer getting the form validation errors in the screenshot.

@brollb @kecso Can you confirm this fixes the issue?
