### ISSUE TITLE
Cannot create project with spaces in project name

### ISSUE THREAD

**Issue by dax-westerman** [webgme/webgme-taxonomy#146]
**Component:** Taxonomy Design Studio
**Area:** Project Creation
**Issue:** Creation of project requires a name without spaces, but there is no feedback to user.
**Steps to Reproduce:**
1. Open the **Projects** dialog
2. Click **Create New**
3. Create a project with a name with spaces; the **Create** button will be grayed out.

![image](https://user-images.githubusercontent.com/11837526/212158624-ecea549a-db60-48c3-8ec7-e8a97aeacd30.png)

4. Add underscores to the project name; the **Create** button will turn active.

![image](https://user-images.githubusercontent.com/11837526/212158653-3c3680cd-e9c2-40bc-a4f6-7d0cb4a13b11.png)

**Severity**
- [x] Low Impact (user can work around)
- [ ] Medium Impact (may cause break in workflow)
- [ ] High Impact (causes break in workflow)

**Type**
- [x] User Feedback
- [x] Functionality
- [ ] Suggestion

**Possible Workaround(s)**
Workaround: Update documentation with note to indicate spaces are not permitted

Example

**Note:** In this version of Taxonomy Studio, project names may not contain spaces.  If the **Create** button is greyed out, please check that the project name is valid.

**Comment by brollb** [comment]
This is limitation in webgme and is outside the scope of this project.
