### ISSUE TITLE
Stream file uploads

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-taxonomy#15]
Uploading files (appending an observation to a dataset) should stream instead of load the file in memory then upload. It should be as simple as setting `body: file.stream()` and `duplex: 'half'` in the call to `this._fetch` [here](https://github.com/webgme/webgme-taxonomy/blob/86898a4d8507b951a234692304b4bf448b7a50ef/src/routers/Search/dashboard/src/Storage.ts#L59).

**Comment by romancow** [comment]
It looks like sending a `ReadableStream` as a request body is "experimental" and not supported by most browsers (https://developer.mozilla.org/en-US/docs/Web/API/Request#browser_compatibility).

Is the intent just to avoid reading the file into a string/buffer? It looks like the `fetch` `body` can be a `Blob`. Will `body: file` not work?

**Comment by brollb** [comment]
Yeah, the intention was to avoid reading the file into memory. Trying the blob sounds good; it's not quite as nice as streaming from the file system but should be an improvement on the current approach.
