### ISSUE TITLE
Hide first term title when selecting tags in tag form

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-taxonomy#153]
After switching to the new human-readable format, the titles for the terms include the path to the root of the taxonomy. This is expected but it also includes the term name at the top (see below).

![DeepinScreenshot_select-area_20230112121836](https://user-images.githubusercontent.com/4982789/212360516-f2bc7ce2-b203-4ebb-a0e2-283631bbc565.png)

**Comment by romancow** [comment]
So running into some issues with getting this to work with a [custom field](https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/).

@brollb Would a css solution be acceptable for this? Just set `display: none` for the offending titles? It looks like the visualizer has a css file it loads. Could we include this css in the router's `index.html` as well?

**Comment by brollb** [comment]
Yeah, that would be fine but it should be in src/common instead so it can be used in the visualizer, too
