### ISSUE TITLE
Test large file uploads

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-taxonomy#160]
We need to test large file uploads to make sure there aren't any surprises during the bootcamp.

**Comment by romancow** [comment]
I've uploaded file size of 512mb numerous times while testing #121. I think probably previous issues with large files was due to not knowing it was uploading in the background. @yogeshVU @brollb You think we can close this one? Or at least close it after #121 is merged?

**Comment by romancow** [comment]
closing since larger files appear to work and now we can see they're progress with https://github.com/webgme/webgme-taxonomy/pull/176
