### ISSUE TITLE
support for exporting human jsonschema at the contentType level

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#177]
Currently, the jsonschema exporter plugin works well at the Taxonomy level, however, for a given content type we would need to support jsonschema exporter which can capture all the vocabularies specific to the given contenttype.

**Comment by brollb** [comment]
It is worth noting that this is already supported by the [module used internally](https://github.com/webgme/webgme-taxonomy/blob/main/src/common/JSONSchemaExporter.js#L25) and just requires an update to the [plugin ](https://github.com/webgme/webgme-taxonomy/blob/main/src/plugins/ExportToJSONSchema/ExportToJSONSchema.js#L25) to match the logic currently used by the [TagCreator router](https://github.com/webgme/webgme-taxonomy/blob/main/src/routers/TagCreator/TagCreator.js#L70-L77).

**Comment by brollb** [comment]
The JSONSchema is generated human-readable content now. (I am not sure exactly when this was changed but it has been this way for a while.)
