### ISSUE TITLE
Content-Type default values

### ISSUE THREAD

**Issue by romancow** [webgme/webgme-taxonomy#182]
### Discussion
Support for setting default value for the terms (or properties of terms) including any of its associated properties.

### Approach
We capture setting of the default values in the taxonomy model representation of the terms in the vocabulary. JSONSchema which captures the taxonomy can also supports setting of the default values for the properties. This JSONSchema could then be used by the tools including TagFormCreator , CLI Scripting, and Dashboard.

(deep-dive topic 1a)

**Comment by brollb** [comment]
A couple other notes about this are that the default values may be set for the content type and not necessarily globally for the terms.
