### ISSUE TITLE
Passing PDP token as header

### ISSUE THREAD

**Issue by romancow** [webgme/webgme-taxonomy#187]
Need to look into passing the PDP token to webgme as a header (and not as a cookie, which is evidently how webGME is currently looking).

I believe this is for the cli.

**Comment by romancow** [comment]
@yogeshVU  - Feel free to expand with any further details on the issue, if you wish.

**Comment by yogeshVU** [comment]
I believe this has been fixed in the main webgme-engine now. hence closing it.
