### ISSUE TITLE
instanceof is not object error

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#19]
If a user is login to the dashboard without any datasets provisioned to the user, the users  sees following screen

![image](https://user-images.githubusercontent.com/8491735/189729241-952d8c35-407d-45e7-821f-ce6bf57302f2.png)

Server log: Uncaught exception:

```
 2022-09-12T18:20:22.825Z - error: uncaughtException: Right-hand side of 'instanceof' is not an object 
```

![image](https://user-images.githubusercontent.com/8491735/189728854-20f355d0-a44d-4400-8cd7-5782cbd09f0c.png)

**Comment by brollb** [comment]
I suspect the error is caused by something else but I added a fix for the error message shown here as that was a bug. Can you give it a try after the PR and see if something else was going on?
