### ISSUE TITLE
Tag form should show vocabulary info in tag dropdown

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-taxonomy#198]
It would be nice to be able to group the terms by vocabulary (or tree in the vocab) to disambiguate between tags with the same name.

**Comment by romancow** [comment]
@yogeshVU Is this not done in some way currently? Each vocabulary is under it's own collapsible header?

**Comment by yogeshVU** [comment]
Yes, this can be closed at the current version shows the vocab subsections in the tag form
