### ISSUE TITLE
convert the observation.json to human readable format

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#20]
current observation.json which is downloaded contains the guid tag format. Need to update it to the human readable format.

**Comment by brollb** [comment]
In that case, do we even want to download the entire observation? Why not just download the metadata or tags?

**Comment by yogeshVU** [comment]
We would need the entire observation, as it also contains other information fields like the dataFile, application dependencies.. and also the creator information..

**Comment by brollb** [comment]
What are we going to use the observation for? I am a little worried our abstractions on top of PDP will be leaky.

**Comment by yogeshVU** [comment]
https://github.com/webgme/webgme-taxonomy/blob/ddff35bdd80e5b84e13f97fd55a98e67928b15a5/src/routers/Search/adapters/PDP/index.js#L181-L182

I added the above conversion logic for guid->human.. I think I am getting some errors here..

**Comment by yogeshVU** [comment]
Observations contains: (metadata+ pdp native logic(app dependencies, index,observer id, etc..
))
