### ISSUE TITLE
Download of file without extension is not happening

### ISSUE THREAD

**Issue by kecso** [webgme/webgme-taxonomy#203]
Apparently uploading a file without extension is working, but downloading it is just not happening...

89d717ae-d298-4672-85d3-5f5037454864_11_0 is an example 
'examplePredictionForLeapFunc_v2' is a file and it has traces in the basic metadata, but it is not downloaded...

'''
[
  {
    "isFunction": false,
    "processType": "bootcampData",
    "processId": "89d717ae-d298-4672-85d3-5f5037454864",
    "isMeasure": true,
    "index": 11,
    "version": 0,
    "observerId": "3a9dc4e3-7507-4ccc-b2f3-631b10f917a5",
    "startTime": null,
    "endTime": null,
    "applicationDependencies": [],
    "processDependencies": [],
    "data": [
      {
        "displayName": "bootcampdata_PRINCETON",
        "taxonomyTags": [
          {
            "fcb3eb50-793e-af31-0cfe-e6a2ef675e3f": {
              "4304256d-93a4-fe64-3b5d-db8e023cdb81": {
                "ebe1305a-d71a-41fc-e11b-126df5638ecb": "Isabel M. Berwian",
                "95619711-481b-bdf5-6ca7-00e833be8bfe": "007",
                "db15b929-a45e-1e6d-bdaf-f6235c445381": {
                  "84803b88-fac1-eb65-1204-488bc44870b4": {}
                }
              }
            }
          }
        ],
        "taxonomyVersion": {
          "branch": "master",
          "commit": "#77ae3ce522e9d7bb26c430ff6c3d79a5263c0231",
          "id": "AllLeap+TaxonomyBootcamp",
          "url": "wellcomewebgme.centralus.cloudapp.azure.com"
        }
      }
    ],
    "dataFiles": [
      "11/includedSupportPackages.txt",
      "11/run_examplePredictionForLeapFunc_v2.sh",
      "11/requiredMCRProducts.txt",
      "11/mccExcludedFiles.log",
      "11/unresolvedSymbols.txt",
      "11/readme.txt",
      "11/examplePredictionForLeapFunc_v2"
    ]
  }
]
'''

it might be an issue with the underlying datalake implementation, but I believe it is reasonable to expect users to upload files without extensions...

**Comment by yogeshVU** [comment]
It appears that we need to pass the file regex expression parameter `filePattern` to capture all the filetypes. By Default it assumes that the files have some extension. Setting the file regex expression to  for parameter `filePattern`  ```**/**``` should capture all the files. https://github.com/webgme/webgme-taxonomy/blob/c6126c084be2ee94e063442eb78f90590bad0e7b/src/routers/Search/src/adapters/PDP/index.ts#L114-L120
