### ISSUE TITLE
Inter-term constraint semantics

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-taxonomy#276]
Currently, inter-term semantics are a little fuzzy. The current behavior is that 0 or more tags can be selected for a content item.

@yogeshVU suggested enforcing at most 1 tag for a given content item. This is appealing as it simplifies things greatly (rather than introducing another level of explicit constraints). However, it would be good to make sure they are sufficiently expressive and not missing some important use-case.

As terms can often be combined and modeled as large, "flat" terms, it's worth considering the different types of property constraints. The current constrained properties are:
- Optional (adds the option of "0" to the subsequent props)
- Enum (1)
- Set (1+)

Terms are constrained with "required" and "optional" selection constraints (recommended isn't a hard constraint).

Given the following constraints, let's flesh out how we can model data with this multiplicity:
1. *0 or 1* - optional enum property or term
2. *exactly 1* - (required) enum in a required term
3. 1 or more - required set in a required term
4. exactly N - not currently possible but could be a set property with constraints
5. N..M - not currently possible but could be a set property with constraints

With the current approach, 1 and 2 are actually not possible to enforce and the suggested change would address it. 

## Are there any other downsides?
One downside is that this implicit (prop type) and prescribed (1 term only) would result in the multiplicity influencing the modeling of the term and would limit the reusability across content types. In other words, if the above constraints were explicitly modeled - like the selection constraints - then it would be easier to define more composable terms that could define content-type-specific multiplicity constraints.

**Comment by kecso** [comment]
The description is a bit fuzzy to me. Do we suggest to move 'related' term under a more complex, singular term?
How are we planning on handling dependencies? (It is relevant as my understanding was that it is a term that can be added to ct without any limitation on their number - as any number of input data can be envisioned for example)

**Comment by brollb** [comment]
With this approach, multiple things (like dependencies) would need to be represented as a set property.

**Comment by brollb** [comment]
Another consideration is the implications for inheritance on the terms if we are using a single object to represent all the metadata for the given item. One tricky thing is that it introduces requirements that are not supported by a single, static JSON schema. That is, we cannot encode that a propery in an object is required based on if another of the properties is set.

I have been a bit skeptical about hierarchical terms for some time and wonder if we could do without them...
