### ISSUE TITLE
Enum based filtering crashes dashboard

### ISSUE THREAD

**Issue by kecso** [webgme/webgme-taxonomy#282]
when selecting an enum value on the dashboard to filter elements, it 'crashes' the page which becomes unresponsive:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '9c05d115-3a71-e1b4-5013-e7c3c7877558')
    at EnumField.isMatch (EnumFilterTag.ts:15:53)
    at App.svelte:91:63
    at Array.find (<anonymous>)
    at App.svelte:91:39
    at Array.every (<anonymous>)
    at App.svelte:90:39
    at App.svelte:109:39
    at Array.filter (<anonymous>)
    at f (App.svelte:109:22)
    at ST.t.$$.update (App.svelte:118:6)

while it might be acceptible for the filter to not work properly, a graceful error handling should be needed immediately!

**Comment by brollb** [comment]
Fixed by https://github.com/webgme/webgme-taxonomy/pull/291
