### ISSUE TITLE
tagformatter should resolve the taxonomy version to use 

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#30]
Given that the Taxonomy will evolve, we need a way to specify which taxonomy file to use for the current dataset.
One potential way is to store that information in the index 0 of the dataset(perhaps the tax vocab, webgmex..)

Else we could end up with the following tag not found error

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/8491735/189970737-0e100f00-710b-434e-90e8-842e1932fd5c.png">

**Comment by brollb** [comment]
This should be configured via the URL. It would be nice to support arbitrary tags though - rather than just branches.

**Comment by brollb** [comment]
I am going to close this for now since it should be covered by #47 and #49 instead.
