### ISSUE TITLE
Error while Downloading tags in TagCreator Form Visualizer 

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#33]
When we press the download button, the download tags completes fine, but the visualizer displays following validation errors

<img width="922" alt="image" src="https://user-images.githubusercontent.com/8491735/189997172-29063bbd-ae1a-46da-8487-ab7f0059f378.png">

**Comment by brollb** [comment]
Fixed as of https://github.com/webgme/webgme-taxonomy/commit/dea79e2d2dc1c93a7ab67f80021497390beaabe2
