### ISSUE TITLE
better error handling for fetchJson response

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#330]
For example, it would be good to see what the response is for this response body

![image](https://github.com/webgme/webgme-taxonomy/assets/8491735/4b7e4809-630b-4e3e-9d3f-49099e597341)

**Comment by brollb** [comment]
I believe this has been addressed using oxide.ts and `fromResult` like here: https://github.com/webgme/webgme-taxonomy/blob/main/src/routers/Search/src/adapters/PDP/index.ts#L154
