### ISSUE TITLE
missing module 'oxide.ts'

### ISSUE THREAD

**Issue by kecso** [webgme/webgme-taxonomy#394]
Using the automatically build docker image, the following error appears at startup:
Error: Cannot find module 'oxide.ts'
taxonomy_1  | Require stack:
taxonomy_1  | - /webgme-taxonomy/src/routers/Search/build/Utils.js
taxonomy_1  | - /webgme-taxonomy/src/routers/Search/build/SystemTerm.js
taxonomy_1  | - /webgme-taxonomy/src/routers/Search/build/index.js
taxonomy_1  | - /webgme-taxonomy/src/routers/Search/Search.js
taxonomy_1  | - /webgme-taxonomy/node_modules/webgme-engine/src/server/standalone.js
taxonomy_1  | - /webgme-taxonomy/node_modules/webgme-engine/index.js
taxonomy_1  | - /webgme-taxonomy/node_modules/webgme/webgme.js
taxonomy_1  | - /webgme-taxonomy/app.js
taxonomy_1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
taxonomy_1  |     at Module._load (node:internal/modules/cjs/loader:922:27)
taxonomy_1  |     at Module.require (node:internal/modules/cjs/loader:1143:19)
taxonomy_1  |     at require (node:internal/modules/cjs/helpers:121:18)
taxonomy_1  |     at Object.<anonymous> (/webgme-taxonomy/src/routers/Search/build/Utils.js:13:20)
taxonomy_1  |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
taxonomy_1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
taxonomy_1  |     at Module.load (node:internal/modules/cjs/loader:1119:32)
taxonomy_1  |     at Module._load (node:internal/modules/cjs/loader:960:12)
taxonomy_1  |     at Module.require (node:internal/modules/cjs/loader:1143:19) {
taxonomy_1  |   code: 'MODULE_NOT_FOUND',
taxonomy_1  |   requireStack: [
taxonomy_1  |     '/webgme-taxonomy/src/routers/Search/build/Utils.js',
taxonomy_1  |     '/webgme-taxonomy/src/routers/Search/build/SystemTerm.js',
taxonomy_1  |     '/webgme-taxonomy/src/routers/Search/build/index.js',
taxonomy_1  |     '/webgme-taxonomy/src/routers/Search/Search.js',
taxonomy_1  |     '/webgme-taxonomy/node_modules/webgme-engine/src/server/standalone.js',
taxonomy_1  |     '/webgme-taxonomy/node_modules/webgme-engine/index.js',
taxonomy_1  |     '/webgme-taxonomy/node_modules/webgme/webgme.js',
taxonomy_1  |     '/webgme-taxonomy/app.js'
taxonomy_1  |   ]
taxonomy_1  | }

**Comment by brollb** [comment]
Thanks, Tamas. This should be fixed by #400
