### ISSUE TITLE
tag latest gives error when no tags available

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#398]
the tag 'latest' gives internal server error if no tags are present on the taxonomy project

**Comment by brollb** [comment]
Could you give a little more context about how to reproduce this? When I create a new project from the "test" seed and the version of the project on main, this is the behavior I see:
![TagLatestError](https://github.com/webgme/webgme-taxonomy/assets/4982789/23c244ca-a400-4711-820d-9a9ce534f14f)

**Comment by brollb** [comment]
Ah, I think I see where you are running into it. This should have been fixed by https://github.com/webgme/webgme-taxonomy/pull/387 and I believe leapdev needs to be updated.

**Comment by brollb** [comment]
Please re-open if the problem persists after updating to the latest docker image. The docker build step in CI was broken for a little bit but should be working now, so the problem should resolve shortly.
