### ISSUE TITLE
Metadata info button does not display data consistently

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#439]
From the dashboard, when user tries to view the metadata of the content, the metadata display info box does not appear for some entries

**Comment by brollb** [comment]
If you open the dev tools, it appears that it is getting an error about the request URI being too large (from nginx). I can change it to a post request as a workaround.

**Comment by yogeshVU** [comment]
![image](https://github.com/webgme/webgme-taxonomy/assets/8491735/7da5d3b8-7348-4970-9d46-ed4c5bfb9068)
