### ISSUE TITLE
Set/list properties for terms

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-taxonomy#45]
Along with integer, text, enum, etc, properties we should support set properties (corresponding to an "anyOf" list in JSON schema).

**Comment by brollb** [comment]
This should basically have the same structure as an enum except allowing the user to select multiple values.

**Comment by brollb** [comment]
To elaborate on this further, currently terms can have a number of different types of properties:
![TermProperties](https://user-images.githubusercontent.com/4982789/202032901-2d300f23-71bd-49e0-be0a-c0c2397525a2.PNG)

However, there is no property type for lists of values. In essence, this is very similar to an enum except allowing multiple selections. For now, I believe a list of compound fields (ie, not supporting other types in the list) would be sufficient. Perhaps @yogeshVU has  motivating example...

**Comment by yogeshVU** [comment]
One use case will be ... list of input datasets {storage objects} for a workflow. For enumfield my understanding is that, we can only select one object from a list of objects(compound objects). as long as we can define a list of objects(compound field will be fine for now) that will be good.

**Comment by romancow** [comment]
@brollb @yogeshVU Should items in the set/list be unique? Or can one item appear multiple ttimes?
