### ISSUE TITLE
metadata.json endpoint returns empty response

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#450]
metadata.json endpoint on the search router is giving empty response.

example url:
`/routers/Search/AllLeap%2BMCPyschTaxonomy/tag/1_1_0/%2FH/artifacts/586370a0-0a42-4c02-a051-174095d894af/2_0/metadata.json`

response:
`{}`

Expected Behavior: response with observation metadata

**Comment by brollb** [comment]
Fixed by #454
