### ISSUE TITLE
Do multiple instances of storage adapters share locks?

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-taxonomy#520]
Looking through the code, it appears that locks (for repositories, etc) aren't actually shared across instances of the adapter - which is a bit problematic.

We should write some tests to confirm this is a problem and fix it.

**Comment by yogeshVU** [comment]
How are locks used in the storage adapters?

**Comment by pmeijer** [comment]
@yogeshVU The "locks" are essentially queues (typically associated with a repository or a content type) of calls where earlier ones are ensured to have finished before another call starts.
You need to make sure you do all work within a queued call as the "lock" is released when the calls resolves (not a limitation but important to keep in mind).

Currently this locking mechanism only works within one webgme-server.

**Comment by yogeshVU** [comment]
Thanks. I was wondering what functionality do the locks serve in the storage adaptor.
