### ISSUE TITLE
Data upload error when uploading only metadata (no data files)

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#539]
When uploading metadata(tag files) we encounter issue related to uploading the new metadata. After the upload, even though there is an error displayed, it however does successfully shows the newly updated metadata.

![image](https://github.com/webgme/webgme-taxonomy/assets/8491735/032c79f5-506c-4c89-b334-3884296a12a2)

**Comment by pmeijer** [comment]
![image_480](https://github.com/webgme/webgme-taxonomy/assets/6518904/cb726883-fc37-4523-a5d7-328cf70d210a)

**Comment by pmeijer** [comment]
from yogesh
"this is the dashboard url used for the participants_sandbox repository: [https://wellcomewebgme.centralus.cloudapp.azure.com/routers/Search/AllLeap%2BMCPyschTaxonomy/branc[…]tatic/index.html?searchQuery=&filterTags=%5B%5D](https://wellcomewebgme.centralus.cloudapp.azure.com/routers/Search/AllLeap%2BMCPyschTaxonomy/branch/master/%2FP/static/index.html?searchQuery=&filterTags=%5B%5D)"
