### ISSUE TITLE
Upload complete notification does not show after successful upload

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#59]
Upload complete notification does not show after successful upload.

**Comment by kecso** [comment]
there are quite a few issues with the notificaiton system snackbar.
it is meant for a single notification at a time and I was not able to find any function that woud programatically remove the 'current' notification and replace it...
there is a timeout, but it does not appear to work (except the default one, which is 5s) - we can try to use that
allegedly there is also a stacked variant, but that does not work either...
not sure how it can be resolved as there is no other notification system ready in svelte mui

**Comment by kecso** [comment]
maybe we could start using this: https://zerodevx.github.io/svelte-toast/

**Comment by kecso** [comment]
Fixed with https://github.com/webgme/webgme-taxonomy/commit/5f61ed1feba5d59a449c9fdf9303ca0a9bd32af7
