### ISSUE TITLE
Missing upload progress status 

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#60]
Currently, when we are uploading a new file, there is no upload status("x percentage of file upload complete", "x amount of time remaining" for instance) indicator. This is problematic, as the user uploads could consists of large file(maybe in 500mb) and there is no way to know the progress activity of the upload(other than perhaps file uploaded successfully at the end).

**Comment by kecso** [comment]
new way of messaging solves this as well (not sophisticated as there is no real time behind the notification, but it progresses :) 
close for now until a real feature is found for this...
Implemented in https://github.com/webgme/webgme-taxonomy/commit/5f61ed1feba5d59a449c9fdf9303ca0a9bd32af7
