### ISSUE TITLE
AzureActiveDirectory missing 

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#61]
When browsing the data dashboard, we encounter following error on the server side:
![image](https://user-images.githubusercontent.com/8491735/193119578-075a5b26-6f3c-4e1d-ae54-76b7a3269b32.png)

and following error on the browser side:
![image](https://user-images.githubusercontent.com/8491735/193119769-0fc9408c-2281-4491-ba16-1b31784ad7b1.png)

**Comment by brollb** [comment]
I have only seen this when the webgme deployment is not configured to work with Azure... Were you logged into Azure & webgme like on the deployment?

**Comment by yogeshVU** [comment]
might have to try this again.

**Comment by brollb** [comment]
Fixed by https://github.com/webgme/webgme-taxonomy/commit/107faacab794dbca8d57312abf28fb627e6aae7a
