### ISSUE TITLE
Add storage component for testing?

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-taxonomy#71]
It would be nice to have a storage component (as an alternative to PDP) to make it easy to test. Perhaps a storage endpoint with fixed data defined in the model?

**Comment by brollb** [comment]
It might make more sense to only have some metadata in the model - like the number of artifact sets to load. Then we can generate the rest dynamically since it shouldn't be tied to the taxonomy (or laborious to make the mock data). However, I guess we could probably take a hybrid approach where we allow some to be defined in the model and the remainder are generated dynamically... (not by any means required for this issue to close but might be nice to keep in mind for testing purposes)

**Comment by yogeshVU** [comment]
We could also look into MongoDB/SQLite(for metadata) along with Minio Object Store(for S3 raw files) for local testing, providing generalization of the storage adaptor.
