### ISSUE TITLE
View/Panel to show the internal records/observations/metadata inside the dataset

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#72]
It would be good to show what the internal records/observations are in each of the datasets.

Usecase: User would like to see what was last uploaded, depending on which the user could upload new set of data. Further, if there was a way to see what is present in each of the datasets, the user can selectively download observations rather then being able to `download all` or `latest`

**Comment by brollb** [comment]
This has been addressed in #74
