### ISSUE TITLE
Define a "base" vocabulary

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-taxonomy#79]
We need to define a base vocabulary which is part of the `taxonomy` seed and contains all the base metadata for uploaded artifacts (including taxonomies themselves).

**Comment by brollb** [comment]
Related notes about requirements:
- needs programmatic/autogenerated terms (upload time, for example). We will need to add a new attribute and update the corresponding code for JSON schema generation, etc.
- the base vocabulary includes terms that don't make sense to present in the standard way (maybe just "name"). This needs to be adjusted accordingly. Should we add another attribute for making it "top-level" in the dashboard or something?

**Comment by brollb** [comment]
The current base vocabulary contains the following terms:
- name
- description
- content
  - location (enum)
  - type (string)
- upload timestamp (autogenerated)
- taxonomy (autogenerated)
- validity

For a first pass, I would focus on updating how the data is stored and making sure the form and dashboard UX isn't changed at all. In other words, these terms in the base vocab shouldn't show up in the form or as a filter in the dashboard (for the first pass anyway).

This entails the following:
- [ ] add the base vocabulary to the metamodel/model (probably to the library itself since it is baked into the language a bit)
- [ ] implement the base vocab as tags
  - [ ] ignore the tags when generating the JSON schema (maybe add an autogenerated field?)
  - [ ] ignore the tags when generating the dashboard config (maybe add a searchable flag to terms for this)
  - [ ] add autogenerated fields when appending data (from endpoints used by the dashboard)
  - [ ] remove the current representation of base vocab content in favor of saving them as actual tags in the observation. (They can still use the same format on the artifacts in the dashboard client and just be converted by the PDP storage adapter or something.)

**Comment by romancow** [comment]
## Base vocabulary review

### Discussion
Started looking at the base vocabulary excel sheet from the box drive.

### Approach
We currently do not populate the base vocabulary, however we will support populating the same soon

_(deep dive topic 3)_
