### ISSUE TITLE
support for system autogenerated taxonomy terms in the base vocab of meta

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#83]
Most of the terms in the base vocab are system generated/populated such as the processID, upload time, etc. Hence there is a need to capture this system generated attribute in the meta.

**Comment by romancow** [comment]
## Auto-populated values using fixed algorithms

### Discussion
Auto-population of tag values occur in several cases: I. loading systems information (GUID, hash and others) in tags, ii. loading autogenerated tag values for content (auto-incremented index and version numbers, upload time, etc.), iii. loading default values in tags, and iv. loading managed dependency information in tags. Special attention needs to be paid to auto-populated tag values when upload occurs via the CLI.

### Approach
Auto-population of tags are implemented by code in taxonomy studio and dashboard tools.

_(deep-dive topic 1d)_

**Comment by brollb** [comment]
System terms should address this more elegantly than our original planned approach.
