### ISSUE TITLE
"Human" JSON schema exporting

### ISSUE THREAD

**Issue by romancow** [webgme/webgme-taxonomy#84]
Add a JSON Schema exporter that supports exporting taxonomy tags in a "human" readable format. This entails using titles as property names instead of GUIDs and removing their IDs. Also, nest enum values directly in the property's `anyOf` (instead of directly under definitions). Enum values also would not need `default` or `const` entries.

This "human" schema should also be accessible via an endpoint, as part of #82.

**Comment by brollb** [comment]
Is this due to the error messages returned when validating over the GUID version? Otherwise, we should be able to convert the tags to GUID format and validate them there, right?

**Comment by yogeshVU** [comment]
Hi @brollb not for validation. To capture the base vocab from the jsonschema and populate the required fields. However, we might be able to generate this `base` json information for the contenttype through an endpoint.

**Comment by brollb** [comment]
(making a note from the meeting) Can we convert validation errors to show the display name instead?
