### ISSUE TITLE
TagCreator form not able to load

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#93]
when loading the tagcreator end point we get following error(similar to localhost:12345/routers/TagCreator/yog_barve_at_vanderbilt_p_edu%2BLEAP_Taxonomy_Release_v1B/branch/master/%2Fz/static/)

![image](https://user-images.githubusercontent.com/8491735/198405097-2cc725fc-625c-4f33-8294-06d2f6e4b29a.png)

**Comment by brollb** [comment]
After looking at the project, it appears that this is an issue with the taxonomy being malformed. The project has been updated.
